# Generated by Django 3.2.4 on 2021-06-28 17:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=300)),
                ('restaurant_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('restaurant_number', models.IntegerField(unique=True)),
                ('restaurant_address', models.CharField(max_length=100)),
                ('restaurant_city', models.CharField(max_length=50)),
                ('restaurant_web', models.URLField(unique=True)),
            ],
        ),
    ]
